//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authority
    {
        public Authority()
        {
            this.Jurisdictions = new HashSet<Jurisdiction>();
        }
    
        public int authId { get; set; }
        public string authName { get; set; }
        public string authAddress { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> numPending { get; set; }
        public Nullable<int> numResolved { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string website { get; set; }
        public string profilePic { get; set; }
        public Nullable<int> flag { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual ICollection<Jurisdiction> Jurisdictions { get; set; }
    }
}
