//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public Complaint()
        {
            this.Comments = new HashSet<Comment>();
            this.Jurisdictions = new HashSet<Jurisdiction>();
            this.Likes = new HashSet<Like>();
            this.Spams = new HashSet<Spam>();
        }
    
        public int complaintId { get; set; }
        public int userId { get; set; }
        public string title { get; set; }
        public string details { get; set; }
        public Nullable<int> numLikes { get; set; }
        public Nullable<int> numComments { get; set; }
        public string picture { get; set; }
        public Nullable<System.DateTime> complaintDate { get; set; }
        public string location { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string category { get; set; }
        public string complaintStatus { get; set; }
        public System.DateTime date { get; set; }
        public int isAnonymous { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string pincode { get; set; }
        public string thumbImage1 { get; set; }
        public string thumbImage2 { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Jurisdiction> Jurisdictions { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public virtual ICollection<Spam> Spams { get; set; }
    }
}
