//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuteAuthority
    {
        public int muteAuthId { get; set; }
        public string muteAuthName { get; set; }
        public string muteAuthAddress { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string website { get; set; }
        public string pic { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> flag { get; set; }
        public string pincode { get; set; }
    }
}
