//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int subscriberId { get; set; }
        public int subscribedToId { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
