//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreService
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Complaints = new HashSet<Complaint>();
            this.Likes = new HashSet<Like>();
            this.Spams = new HashSet<Spam>();
            this.Subscriptions = new HashSet<Subscription>();
            this.Subscriptions1 = new HashSet<Subscription>();
        }
    
        public int userId { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public string pwd { get; set; }
        public string phone { get; set; }
        public string userAddress { get; set; }
        public Nullable<double> points { get; set; }
        public string userRank { get; set; }
        public string profilePic { get; set; }
        public string webURI { get; set; }
        public string phoneURI { get; set; }
        public Nullable<int> numComplaints { get; set; }
        public System.DateTime date { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string pincode { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Complaint> Complaints { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public virtual ICollection<Spam> Spams { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<Subscription> Subscriptions1 { get; set; }
    }
}
